
// Action IDs
export const HANDLE_SIGN_IN= "HANDLE_SIGN_IN";
export const HANDLE_SIGN_OUT= "HANDLE_SIGN_OUT";
export const HANDLE_SIGN_IN_ERROR= "HANDLE_SIGN_IN_ERROR";
export const RESET_SIGN_IN_ERROR = "RESET_SIGN_IN_ERROR";
export const SET_GOOGLE_AUTH= "SET_GOOGLE_AUTH";
export const HANDLE_GOOGLE_AUTH_SIGN_IN= "HANDLE_GOOGLE_AUTH_SIGN_IN";
export const HANDLE_GOOGLE_AUTH_SIGN_OUT= "HANDLE_GOOGLE_AUTH_SIGN_OUT";
export const HANDLE_SIGN_UP_ERROR= "HANDLE_SIGN_UP_ERROR";
export const RESET_SIGN_UP= "RESET_SIGN_UP";
export const HANDLE_TAB_HOVER_EVENT = "HANDLE_TAB_HOVER_EVENT";

export const LOAD_HOME_PAGE = "LOAD_HOME_PAGE";
export const LOAD_FILTER_PRODUCTS = "LOAD_FILTER_PRODUCTS";
export const LOAD_FILTER_ATTRIBUTES = "LOAD_FILTER_ATTRIBUTES";
export const LOAD_SHOPPING_BAG_PRODUCTS = "LOAD_SHOPPING_BAG_PRODUCTS";
export const RESET_SHOPPING_BAG_PRODUCTS = "RESET_SHOPPING_BAG_PRODUCTS";
export const LOAD_TABS_DATA = "LOAD_TABS_DATA";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

export const REMOVE_FILTER_ATTRIBUTES = "REMOVE_FILTER_ATTRIBUTES";
export const SELECT_SORT_CATEGORY = "SELECT_SORT_CATEGORY";
export const RESET_SELECT_SORT_CATEGORY = "RESET_SELECT_SORT_CATEGORY";
export const SELECT_PRODUCT_PAGE = "SELECT_PRODUCT_PAGE";
export const RESET_SELECT_PRODUCT_PAGE = "RESET_SELECT_PRODUCT_PAGE";
export const SELECT_PRODUCT_DETAIL = "SELECT_PRODUCT_DETAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const RESET_ADD_TO_CART = "RESET_ADD_TO_CART";
export const CART_TOTAL = "CART_TOTAL";
export const RESET_CART_TOTAL = "RESET_CART_TOTAL";
export const DELIVERY_CHARGES = "DELIVERY_CHARGES";
export const RESET_DELIVERY_CHARGES = "RESET_DELIVERY_CHARGES";

export const SAVE_QUERY_STATUS = "SAVE_QUERY_STATUS";
export const RESET_QUERY_STATUS = "RESET_QUERY_STATUS";
export const LOAD_SELECTED_CATEGORY_FROM_URL = "LOAD_SELECTED_CATEGORY_FROM_URL";
export const ADD_SELECTED_CATEGORY = "ADD_SELECTED_CATEGORY";
export const REMOVE_SELECTED_CATEGORY = "REMOVE_SELECTED_CATEGORY";
export const RESET_SELECTED_CATEGORY = "RESET_SELECTED_CATEGORY";
export const SAVE_SORT_LIST = "SAVE_SORT_LIST";
export const SHIPPING_ADDRESS_CONFIRMED = "SHIPPING_ADDRESS_CONFIRMED";
export const RESET_SHIPPING_ADDRESS = "RESET_SHIPPING_ADDRESS";
export const SHIPPING_OPTION_CONFIRMED = "SHIPPING_OPTION_CONFIRMED";
export const RESET_SHIPPING_OPTION = "RESET_SHIPPING_OPTION";
export const PAYMENT_INFO_CONFIRMED = "PAYMENT_INFO_CONFIRMED";
export const PAYMENT_RESPONSE = "PAYMENT_RESPONSE";
export const PAYMENT_RESPONSE_ERROR = "PAYMENT_RESPONSE_ERROR";
export const RESET_PAYMENT_RESPONSE = "RESET_PAYMENT_RESPONSE";
export const RESET_PAYMENT_RESPONSE_ERROR = "RESET_PAYMENT_RESPONSE_ERROR";

export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const SEARCH_KEYWORD_ERROR = "SEARCH_KEYWORD_ERROR";


