
// Action IDs
export const HANDLE_SIGN_IN= "HANDLE_SIGN_IN";
export const HANDLE_SIGN_OUT= "HANDLE_SIGN_OUT";
export const HANDLE_SIGN_UP= "HANDLE_SIGN_UP";
export const HANDLE_SIGN_IN_ERROR= "HANDLE_SIGN_IN_ERROR";
export const HANDLE_SIGN_UP_ERROR= "HANDLE_SIGN_UP_ERROR";
export const HANDLE_TAB_HOVER_EVENT = "HANDLE_TAB_HOVER_EVENT";

export const LOAD_HOME_PAGE = "LOAD_HOME_PAGE";
export const LOAD_FILTER_PRODUCTS = "LOAD_FILTER_PRODUCTS";
export const LOAD_FILTER_ATTRIBUTES = "LOAD_FILTER_ATTRIBUTES";
export const LOAD_SHOPPING_BAG_PRODUCTS = "LOAD_SHOPPING_BAG_PRODUCTS";
export const LOAD_TABS_DATA = "LOAD_TABS_DATA";

export const REMOVE_FILTER_ATTRIBUTES = "REMOVE_FILTER_ATTRIBUTES";
export const SELECT_SORT_CATEGORY = "SELECT_SORT_CATEGORY";
export const SELECT_PRODUCT_PAGE = "SELECT_PRODUCT_PAGE";
export const SELECT_PRODUCT_DETAIL = "SELECT_PRODUCT_DETAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const CART_TOTAL = "CART_TOTAL";

export const SAVE_QUERY_STATUS = "SAVE_QUERY_STATUS";
export const ADD_SELECTED_CATEGORY = "ADD_SELECTED_CATEGORY";
export const REMOVE_SELECTED_CATEGORY = "REMOVE_SELECTED_CATEGORY";
export const SAVE_SORT_LIST = "SAVE_SORT_LIST";

// js cookie IDs
export const HANDLE_TOKEN_ID = "HANDLE_TOKEN_ID";
export const SHOPPERS_PRODUCT_ID = 'SHOPPERS_PRODUCT_ID';

// http error codes
export const INTERNAL_SERVER_ERROR_CODE = 500;
export const BAD_REQUEST_ERROR_CODE = 400;

// API URL
export const HOME_PAGE_DATA_API = "/home";
export const TABS_DATA_API = "/tabs";
export const PRODUCT_BY_ID_DATA_API = "/products?product_id=";
export const PRODUCT_BY_CATEGORY_DATA_API = "/products?q=";

// attributes length
export const HOME_PAGE_API_OBJECT_LEN = 3;
export const TABS_API_OBJECT_LEN = 6;
